apps/solar/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [

    url(r'^request-offer/(?P<uuid>[\w-]+)/$',
        views.RequestOfferView.as_view(),
        name='request_offer',
        ),
    url(r'^assessment/(?P<pk>[0-9]+)/notes/update/$',
        views.AssessmentNotesUpdateView.as_view(),
        name='assessment_notes_update',
        ),

    url(r'^area/$', views.SelectAreaView.as_view(), name='area'),
    url(r'^area/(?P<location_uuid>[\w-]+)/$', views.SelectAreaView.as_view(), name='area'),
    url(r'^no-data/$', views.NoDataView.as_view(), name='no_data'),
    url(r'^assessment/example/(?P<slug>[\w-]+)/$', views.ExampleAssessmentView.as_view(), name='example_assessment'),
    url(r'^assessment/example/$', views.ExampleAssessmentView.as_view(), name='example_assessment'),
    url(r'^assessment/(?P<uuid>[\w-]+)/connect-linkedin/$', views.connect_linkedin_view, name='connect_linkedin'),
    url(r'^assessment/(?P<uuid>[\w-]+)/signup/$', views.AssessmentSignupModalView.as_view(), name='assessment_signup_modal'),
    url(r'^assessment/(?P<uuid>[\w-]+)/shared/$', views.SharedAssessmentView.as_view(), name='shared_assessment'),
    url(r'^assessment/(?P<uuid>[\w-]+)/overlay/$', views.AssessmentOverlayView.as_view(), name='assessment_overlay'),
    url(r'^assessment/(?P<uuid>[\w-]+)/$', views.AssessmentView.as_view(), name='assessment'),
    url(r'^assessmentml/(?P<uuid>[\w-]+)/$', views.AssessmentViewML.as_view(), name='assessmentml'),
    url(r'^send-report/(?P<uuid>[\w-]+)/$', views.SendReportView.as_view(), name='send_report'),
    url(r'^thank-you/$', views.ThankYouView.as_view(), name='thank_you'),
]

apps/support/urls.py
from django.conf.urls import url

from .views import *


urlpatterns = [
    url(r'^$', SupportPageView.as_view(), name='support'),
    url(r'^call-request-success/$', CallRequestSuccessView.as_view(), name='call_request_success')
]

powermarket/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.core.urlresolvers import reverse_lazy
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.views.generic import TemplateView

import private_storage.urls
from rest_framework.routers import DefaultRouter

from powermarket.views import OopsView
from apps.landing.views import LandingPageView
from apps.solar.views import report_link_view
from apps.solar import api as solar_api
from .sitemaps import *
from .views import *


admin.autodiscover()

handler400 = OopsView.as_view()
handler403 = OopsView.as_view()
handler404 = OopsView.as_view()
handler500 = OopsView.as_view()

sitemaps = {
    'static_pages': StaticPagesSitemap,
    'blog_pages': BlogPagesSitemap,
    'dynamic_pages': DynamicPagesSitemap,
    'allauth': AllauthSitemap,
    'supplier_app': SupplierAppSitemap,
    'solar_app': SolarAppSitemap,
    'support_app': SupportAppSitemap,
}

router = DefaultRouter()
router.register(r'solar-potential/assessment', solar_api.AssessmentViewSet)

api_urlpatterns = router.urls
api_urlpatterns += [
    url(r'^solar/environmental-benefits/?(?P<energy>[a-zA-Z0-9_.-]*)/$',
        solar_api.EnvironmentalBenefitsAPIView.as_view(),
        name='environmental_benefits',
        ),
    url(r'^solar/fit-rate/(?P<annual_energy>[0-9.]*)/(?P<target_date>[0-9-]*)$',
        solar_api.FitRateAPIView.as_view(),
        name='fit_rate',
        )
]

urlpatterns = [

    url(r'^admin/', include(admin.site.urls)),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^impersonate/', include('impersonate.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^hello/$', LandingPageView.as_view(), name='hello'),
    url(r'^', include('apps.landing.urls')),
    url(r'^', include('apps.manager.urls', namespace='manager')),
    url(r'^user/', include('apps.user.urls', namespace='user')),
    url(r'^support/', include('apps.support.urls', namespace='support')),
    url(r'^supplier/', include('apps.supplier.urls', namespace='supplier')),
    url(r'^solar/', include('apps.solar.urls', namespace='solar')),
    url(r'^r/(?P<uuid>[a-zA-Z0-9_.-]*)/$', report_link_view, name='report_link'),
    url(r'^api/', include(api_urlpatterns, namespace='api')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url('^private/', include(private_storage.urls)),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    url(r'^email-test/$', EmailTestView.as_view()),
    url(r'^email-test/(?P<template_name>[\w-]+)/?$', EmailTestView.as_view()),
    url(r'^coming-soon/$', ComingSoonModalView.as_view(), name='coming_soon'),
    url(r'^400/$', OopsView.as_view(), name='400'),
    url(r'^403/$', OopsView.as_view(), name='403'),
    url(r'^404/$', OopsView.as_view(), name='404'),
    url(r'^500/$', OopsView.as_view(), name='500'),
    url(r'^oops/$', OopsView.as_view(), name='oops'),
    url(r'^.*/$', OopsView.as_view())

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/solar/forms.py
from django.contrib.gis import forms
from django.utils.translation import ugettext_lazy as _

from allauth.account.forms import SignupForm

from apps.user.models import Contact


class SelectAreaForm(forms.Form):
    mpoly = forms.CharField(
        widget=forms.HiddenInput(),
        required=False,
    )
    selected_area = forms.CharField(
        label='',
        widget=forms.HiddenInput(),
        required=False,
    )


class AssessmentSignupForm(SignupForm):
    required_css_class = 'required'
    error_css_class = 'error'

    assessment_uuid = forms.CharField(
        widget=forms.HiddenInput(),
    )
    email = forms.EmailField(
        label='',
        widget=forms.TextInput(
            attrs={
                'placeholder': _('Your email'),
                'class': 'input-lg',
            },
        ),
    )
    password1 = forms.CharField(
        label='',
        widget=forms.PasswordInput(
            attrs={
                'placeholder': _('Choose password'),
                'class': 'input-lg',
            },
        ),
    )

    def __init__(self, *args, **kwargs):
        super(AssessmentSignupForm, self).__init__(*args, **kwargs)
        # The label attribute in the field definition
        # does not work, probably bc there is some magic
        # going on due to email/username options.
        self.fields['email'].label = ''


class ContactForm(forms.ModelForm):
    required_css_class = 'required'
    error_css_class = 'error'

    assessment_uuid = forms.CharField(widget=forms.HiddenInput())

    class Meta:
        model = Contact
        fields = (
            'name',
            'email',
            'phone',
        )
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'eg. John Smith'}),
            'email': forms.EmailInput(attrs={'placeholder': 'eg. john@example.com'}),
            'phone': forms.TextInput(attrs={'placeholder': 'eg. 07123456789'}),
        }

apps/solar/views.py
from django.conf import settings
from django.contrib.gis.geos import (
    GEOSGeometry,
    Point,
)
from django.contrib.sites.shortcuts import get_current_site
from django.core.urlresolvers import (
    reverse,
    reverse_lazy,
)
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import (
    get_object_or_404,
    redirect,
)
from django.utils.translation import ugettext_lazy as _
from django.views.generic import (
    CreateView,
    FormView,
    TemplateView,
    UpdateView,
)

from allauth.account import app_settings as account_app_settings
from allauth.account.utils import complete_signup
from allauth.account.views import SignupView

from powermarket.choices import (
    CURRENCY_GBP,
    CURRENCY_INR,
)
from powermarket.email import send_templated_email
from powermarket.mixins import ModalResponseMixin
from apps.location.models import Location
from apps.manager.models import Project
from apps.nrel.pvwatts5 import pvwatts5_request
from apps.nrel.models import NoDataError
from apps.user.models import Contact
from .calculations import calc_monthly_profit
from .forms import (
    SelectAreaForm,
    AssessmentSignupForm,
    ContactForm,
)
from .models import (
    Assessment,
    ExampleAssessment,
)


class SelectAreaView(FormView):
    template_name = 'solar/select_area.html'
    form_class = SelectAreaForm
    address = settings.DEFAULT_ADDRESS
    location = None

    def dispatch(self, request, *args, **kwargs):
        try:
            self.location = Location.objects.get(uuid=self.kwargs.get('location_uuid'))
            if self.location.address:
                self.address = self.location.address
        except:
            pass
        return super(SelectAreaView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(SelectAreaView, self).get_context_data(**kwargs)
        context['address'] = self.address
        return context

    def form_valid(self, form, **kwargs):
        mpoly = GEOSGeometry(form.cleaned_data['mpoly'])
        area = float(form.cleaned_data['selected_area'])
        # Until we add the ML estimation of tilt and azimuth, assume tilt=latitude and azimuth=180(Northern hemisphere) or 0 (S hemi)
        tilt=mpoly.centroid[0]
        if mpoly.centroid[0]>=0:
            azimuth=180
        else:
            azimuth=0

        location = self.location
        if location.country and location.country.name == 'India':
            nrel_results = pvwatts5_request(mpoly.centroid, area, tilt, azimuth, dataset='IN')
            inputs = nrel_results.get('inputs')
            outputs = nrel_results.get('outputs')
        else:
            nrel_results = pvwatts5_request(mpoly.centroid, area, tilt, azimuth)
            inputs = nrel_results.get('inputs')
            outputs = nrel_results.get('outputs')
            if not outputs:
                nrel_results = pvwatts5_request(mpoly.centroid, area, tilt, azimuth, dataset='tmy2')
                inputs = nrel_results.get('inputs')
                outputs = nrel_results.get('outputs')

        if not outputs: # handle no NREL data
            lat = float(inputs.get('lat'))
            lon = float(inputs.get('lon'))
            NoDataError.objects.create(location=Point(lon, lat))
            return HttpResponseRedirect(reverse('solar:no_data'))

        system_capacity_estimate = inputs.get('system_capacity')  # nameplate capacity in kW.
        ac_monthly = outputs.get('ac_monthly')
        ac_annual = outputs.get('ac_annual')

        country = 'United Kingdom'
        state = None
        currency = CURRENCY_GBP
        if location.country:
            if location.country.name == 'India':
                currency = CURRENCY_INR
                country = 'India'
                if location.administrative_area_level_1:
                    # TODO:
                    # Test and correct state names if necessary.
                    state = location.administrative_area_level_1

        monthly_savings, monthly_earnings = calc_monthly_profit(ac_monthly, country=country, state=state)

        assessment = Assessment(
            mpoly=mpoly,
            num_points=mpoly.num_points,
            location=location,
            selected_area=area,
            system_capacity_estimate=system_capacity_estimate,
            monthly_energy_estimates=ac_monthly,
            monthly_savings_estimates=monthly_savings,
            monthly_earnings_estimates=monthly_earnings,
            annual_energy_estimate=ac_annual,
            annual_savings_estimate=sum(monthly_savings),
            annual_earnings_estimate=sum(monthly_earnings),
            nrel_version=nrel_results.get('version'),
            nrel_station_distance=nrel_results.get('station_info').get('distance') / 1000,  # [km]
            currency=currency,
        )

        user = self.request.user
        if user.is_authenticated():
            Assessment.objects.filter(project__profile=user.profile).delete()
            assessment.project = user.profile.projects.first()

        assessment.save()

        send_templated_email(
            subject='PowerMarket Assessment Created',
            recipient_list=settings.MANAGERS,
            text_template='notification_email/assessment_created.txt',
            context={
                'short_link': 'https://' + get_current_site(self.request).domain + assessment.short_link,
            },
            fail_silently=True,
        )

        return HttpResponseRedirect(
            reverse(
                'solar:assessment',
                kwargs={'uuid': assessment.uuid},
            )
        )

class AssessmentOverlayView(CreateView):
    template_name = 'solar/assessment_overlay.html'
    form_class = ContactForm
    assessment = None

    def dispatch(self, request, *args, **kwargs):
        self.assessment = get_object_or_404(Assessment, uuid=kwargs['uuid'])
        if (self.assessment.contact or self.assessment.project
                or request.user.is_staff or self.assessment.supervised):
            return HttpResponseRedirect(
                reverse(
                    'solar:assessment',
                    kwargs={'uuid': self.assessment.uuid},
                )
            )
        return super(AssessmentOverlayView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(AssessmentOverlayView, self).get_context_data(**kwargs)
        context['assessment'] = self.assessment
        return context

    def get_initial(self):
        initial = super(AssessmentOverlayView, self).get_initial()
        initial['assessment_uuid'] = self.assessment
        return initial

    def form_valid(self, form):
        contact = form.save()
        self.assessment = get_object_or_404(Assessment, uuid=form.cleaned_data['assessment_uuid'])
        self.assessment.contact = contact

        short_link = 'https://' + get_current_site(self.request).domain + self.assessment.short_link

        email = send_templated_email(
            subject='Your PowerMarket Solar Report',
            recipient_list=(contact.email,),
            text_template='email/text/solar_potential_assessment.txt',
            html_template='email/html/solar_potential_assessment.html',
            context={
                'name': contact.name,
                'assessment': self.assessment,
            },
            fail_silently=True,
        )
        if email == 1:
            self.assessment.email_sent = True

        self.assessment.save()

        send_templated_email(
            subject='PowerMarket contact created',
            recipient_list=settings.MANAGERS,
            text_template='notification_email/contact_created.txt',
            context={
                'name': contact.name,
                'email': contact.email,
                'phone': contact.phone,
                'short_link': short_link,
            },
            fail_silently=True,
        )

        return HttpResponseRedirect(reverse('solar:assessment', kwargs={'uuid': self.assessment.uuid}))


def connect_linkedin_view(request, uuid):
    user = request.user
    profile = user.profile

    socialaccount = user.socialaccount_set.first()

    profile.first_name = socialaccount.extra_data.get('firstName')
    profile.last_name = socialaccount.extra_data.get('lastName')
    profile.linkedin_url = socialaccount.extra_data.get('publicProfileUrl')
    profile.save()

    project = Project.objects.get(profile=user.profile)
    assessment = Assessment.objects.get(uuid=uuid)
    assessment.project = project

    short_link = 'http://' + get_current_site(request).domain + assessment.short_link

    name = "{first_name} {last_name}".format(
        first_name=profile.first_name,
        last_name=profile.last_name,
    )

    email = socialaccount.extra_data.get('emailAddress')

    email_status = send_templated_email(
        subject='Your PowerMarket Solar Report',
        recipient_list=(user.email,),
        text_template='email/text/solar_potential_assessment.txt',
        html_template='email/html/solar_potential_assessment.html',
        context={
            'name': name,
            'assessment': assessment,
        },
        fail_silently=True,
    )
    if email_status == 1:
        assessment.email_sent = True

    assessment.save()

    project.update_stage()
    project.save()

    send_templated_email(
        subject='PowerMarket LinkedIn contact created',
        recipient_list=settings.MANAGERS,
        text_template='notification_email/contact_created.txt',
        context={
            'name': name,
            'email': email,
            'short_link': short_link,
        },
        fail_silently=True,
    )

    return HttpResponseRedirect(reverse('solar:assessment', kwargs={'uuid': assessment.uuid}))


'''
class AssessmentView(TemplateView):
    template_name = 'solar/assessment.html'
    assessment = None

apps/solar/templates/solar/no_data.html
{% extends "solar/solar_base.html" %}
{% load i18n static %}

{% block meta_title %}{{ block.super }} - Thank you{% endblock %}

{% block meta_description %}
    {% trans "We couldn't retrieve any data for this location." context "Meta description." %}
{% endblock %}

{% block styles %}<link href="{% static 'css/thank_you.css' %}" rel="stylesheet">{% endblock %}

{% block content %}
    <div class="section-tight">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <h1>Sorry!</h1>
                    <h4>We couldn't retrieve any data for this location. Click the button below if you want to make another selection.</h4>
                    <br/>
                    <p>
                        <a href="{% url 'solar:area' %}" class="btn btn-lg btn-primary">Select area</a>
                    </p>
                    <br/>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

apps/solar/templates/solar/select_area.html
{% extends "solar/solar_base.html" %}
{% load i18n static bootstrap3 svg %}

{% block meta_title %}{% trans "Select region(s)" context "Select region(s): meta title." %} - {{ block.super }}{% endblock %}
{% block meta_description %}{% trans "Select region(s) you think are suitable for solar panels." context "Select region(s): meta description." %}{% endblock %}

{% block styles %}<link rel="stylesheet" href="{% static 'css/select_area.css' %}">{% endblock %}

{% block navbar_subtitle %}{% trans 'Select region(s)' context 'Select area: navbar subtitle.' %}{% endblock %}
{% block navbar_right %}
    <li><a href="{% url 'support:support' %}">{% trans 'Support' context 'Navbar item.' %}</a></li>
    {% if not user.is_authenticated %}
        <li><a href="{% url 'account_login' %}">{% trans 'Login' context 'Navbar button.' %}</a></li>
    {% else %}
        <li><a href="{% url 'account_logout' %}" {% comment %}data-toggle="tooltip" data-placement="bottom" title="{% trans 'Logout' context 'Navbar tooltip.' %}"{% endcomment %}><i class="fa fa-power-off"></i> &nbsp;  {% trans 'Logout' context 'Navbar item.' %}</a></li>
    {% endif %}
{% endblock %}

{% block navbar_extra %}

{% endblock %}

{% block content %}
    <div class="controls-container">
        <form id="select-area-form" novalidate method="POST">
            {% csrf_token %}
            {{ form.mpoly }}
            {{ form.selected_area }}
        </form>
        <div id="location-input-container" class="controls">
            <div class="controls-content">
                <div class="controls-icon"><i class="glyphicon glyphicon-map-marker danger-text"></i></div>
                <input id="pac-input" type="text" placeholder="Search Box" value="{{ address }}" disabled="disabled">
            </div>
        </div>
        <div class="controls">
            <div class="controls-content controls-icon"><span class="svg-icon">{% svg 'noun-polygon' %}</span></div>
            <div id="polygon-control-0" class="polygon-control dropdown controls-content selected" data-polygon-id="0">
                <div class="dropdown-toggle" id="polygon-dropdown-0" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">1</div>
                <ul class="dropdown-menu" aria-labelledby="polygon-dropdown-0">
                    {% comment %}<li class="dropdown-header">Polygon 1</li>{% endcomment %}
                    <li><div class="control-item select-polygon"><i class="fa fa-mouse-pointer"></i> &nbsp; Select</div></li>
                    <li><div class="control-item clear-markers"><i class="fa fa-times"></i> &nbsp; Clear</div></li>
                    <li><div class="control-item remove-polygon"><i class="fa fa-trash"></i> &nbsp; Remove</div></li>
                    {% comment %}
                    <li role="separator" class="divider"></li>
                    <li class="dropdown-header">Change color</li>
                    <li>
                        <div class="color-patch-container">
                            <div class="color-patch color-1 pointer"></div>
                            <div class="color-patch color-2 pointer"></div>
                            <div class="color-patch color-3 pointer"></div>
                            <div class="color-patch color-4 pointer"></div>
                        </div>
                    </li>
                    {% endcomment %}
                </ul>
            </div>
            <div id="polygon-add-btn" class="controls-content polygon-control"><i class="fa fa-plus"></i></div>
            <div id="polygon-help-btn" class="controls-content polygon-control"><i class="fa fa-question-circle-o"></i></div>
        </div>
        {% comment %}<div class="controls">
            <div class="controls-content">
                <div class="help-btn">
                    <i class="fa fa-question-circle"></i>
                </div>
            </div>
        </div>{% endcomment %}
        <div class="inline-block controls-btn">
            <a href="javascript:submitForm();" class="btn btn-primary create-report-btn"><i class="fa fa-arrow-right"></i> &nbsp; {% trans 'Estimate Solar Potential' context 'Control btn label.' %}</a>
        </div>



        <br/>
        <div class="inline-block controls-btn">
            <a href="/" class="btn btn-secondary"><i class="fa fa-arrow-right"></i> &nbsp; {% trans 'Change Location' context 'Control btn label.' %}</a>
        </div>
        <br/>
        <div class="intro-container controls">
            <div class="intro-container-content">
                <p>
                    <a id="close-intro-btn" href="#" class="btn btn-primary" style="float:right">{% trans 'X' context 'Intro btn label.' %}</a>
                </p>
                <h2>{% trans 'Draw around the region(s) you want to assess' context 'Page title.' %}</h2>
                <hr>
                <div class="col-intro-container">
                    <div class="col-intro-scroll">
                        <div class="col-intro">
                            <h4>Adjust location</h4>
                            <p><small>Click-and-drag the map to fine-tune the location, and use the +/- at bottom right to zoom in or out.  If you want assess a different location click Change Location:</small></p>
                            <div class="animation">
                                <img src="{% static 'img/address-input_300x160.jpg' %}" alt="Google Maps location autocomplete" />
                            </div>
                        </div>
                        <div class="col-intro">
                            <h4>Draw region</h4>
                            <p><small>Click on the image to draw around the region you would like to assess for solar. Click again on a marker to remove it, click-and-drag to move it.</small></p>
                            <div class="animation">
                                <img src="{% static 'animations/select-area-animation_300x160.gif' %}" alt="Select roof area" />
                            </div>
                        </div>
                        <div class="col-intro">
                            <h4>Add more regions</h4>
                            <p><small>You can draw around more than one region.  Click on the <b>+</b> button above to add more regions and on 1, 2... to edit, clear or remove regions you've already drawn</small></p>
                            <div class="animation">
                                <img src="{% static 'img/multi-polygon_300x160.jpg' %}" alt="Multi-polygon selection" />
                            </div>
                        </div>
                    </div>
                </div>
                <p style="text-align:right">
                    {% comment %}<a id="demo-video-btn" href="https://youtu.be/-G7AN4KSKWk" target="_blank" class="btn btn-lg btn-primary"><i class="fa fa-play-circle-o"></i> &nbsp; {% trans 'Watch demo video' context 'Intro btn label.' %}</a> &nbsp;&nbsp;{% endcomment %}
                    <a id="close-intro-btn2" href="#" class="btn btn-primary">{% trans 'Close This Info Box' context 'Intro btn label.' %}</a>
                </p>
            </div>
        </div>
    </div>
    <div class="map-container">
        <div id="map"></div>
    </div>
    <div class="location-not-found collapse">
        <div class="container section-tight">
            <div class="row">
                <div class="col-sm-12">
                    <h2>{% trans 'Sorry, we couldn\'t find that location.' context 'Page title.' %}</h2>
                    <h4>{% trans 'Maybe a spelling error? Please, try again.' context 'Page subtitle.' %}</h4>
                    <br/>
                    <p><a href="{% url 'landing_page' %}" class="btn btn-primary">{% trans 'Back to landing page' context 'Btn label.' %}</a></p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block footer_container %}{% endblock %}

{% block scripts %}
    <script src="{{ settings.HTTP_PROTOCOL }}://maps.google.com/maps/api/js?key={{ settings.MAPS_API_KEY }}&libraries=places&language=en"></script>
    <script src="{% static 'js/select_area.js' %}"></script>

{% endblock %}

{% block zopim_widget %}{% endblock %}

apps/solar/templates/solar/solar_base.html
{% extends 'base.html' %}
{% load i18n %}

{% block navbar_subtitle %}{% trans 'Solar Energy' context 'Solar: navbar subtitle.' %}{% endblock %}

{% block shoutout %}{% endblock %}

apps/solar/templates/solar/thank_you.html
{% extends "solar/solar_base.html" %}
{% load i18n static %}

{% block meta_title %}{{ block.super }} - Thank you{% endblock %}

{% block meta_description %}
    {% trans "Thank you for helping to save the environment." context "Meta description." %}
{% endblock %}

{% block styles %}<link href="{% static 'css/thank_you.css' %}" rel="stylesheet">{% endblock %}

{% block content %}
    <div class="thank-you-container">
        <div class="section-tight">
            <div class="container">
                <div class="row">
                    <div class="col-xs-12 col-md-6 col-md-offset-3">
                        <div class="thank-you-content-container">
                            <h1>Thank you!</h1>
                            <h3>Check your inbox.</h3>
                            {% comment %}<p>
                                <a href="https://www.linkedin.com/company/power-market" target="_blank" class="social-icon-container"><i class="fa fa-linkedin"></i></a>&nbsp;&nbsp;
                                <a href="https://twitter.com/Powermarketuk" target="_blank" class="social-icon-container"><i class="fa fa-twitter"></i></a>&nbsp;&nbsp;
                                <a href="https://medium.com/@powermarket" target="_blank" class="social-icon-container"><i class="fa fa-medium"></i></a>&nbsp;&nbsp;
                            </p>{% endcomment %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}